INSERT INTO ROLE_TABLE VALUES (1, 'ROLE_USER');
INSERT INTO ROLE_TABLE VALUES (2, 'ROLE_ADMIN');
INSERT INTO USER_TABLE VALUES (1, 'user', 'user', 1);
INSERT INTO USER_TABLE VALUES (2, 'admin', 'admin', 2);
