DROP TABLE IF EXISTS ROLE_TABLE;
CREATE TABLE ROLE_TABLE (
role_id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS USER_TABLE;
CREATE TABLE USER_TABLE (
user_id INT AUTO_INCREMENT  PRIMARY KEY,
login VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
role_id INT NOT NULL
);
